### ISSUE TITLE
Repair permissions

### ISSUE THREAD

**Issue by bumblebritches57** [herrbischoff/awesome-osx-command-line#115]
Your permissions can still get messed up, and the new command to fix them is: sudo /usr/libexec/repair_packages --repair --standard-pkgs

This is new to El Capitan.

**Comment by herrbischoff** [comment]
Thanks for this interesting catch. However, upon trying and researching it, it's about as (in)efficient as the "old" permission repair. It is not able to completely repair every instance it finds differing in permissions.

Also, when using Homebrew, it resets the user:group of `/usr/local` to `root:wheel`, effectively removing write permissions for the current user. This breaks Homebrew. I may add this to the collection with this result as a caveat.

Anyway, good catch!

**Comment by Eitot** [comment]
This command was not new to El Capitan, it existed since permissions repair existed. The libexec directory normally contains binaries that are used by other programs, in this case presumably by Disk Utility itself. In El Capitan, Apple severed this usage and in Sierra they removed this command entirely. Even `pkgutil` can no longer repair packages (Apple seems to have forgotten to update this program).

**Comment by herrbischoff** [comment]
Since the suggested command is entirely deprecated, I'm going to close this issue without adding it to the list.
