### ISSUE TITLE
Can one tile wallpaper images from the command line?

### ISSUE THREAD

**Issue by sleekweasel** [herrbischoff/awesome-osx-command-line#177]
Great resource, and great idea!

Tiled wallpaper images?

**Comment by herrbischoff** [comment]
I've looked into it, as it is a SQLite database storing all the relevant information. Since it's quite opaque what exactly gets changed and why, you will have to dig into that yourself. The database is located at `~/Library/Application Support/Dock/desktoppicture.db`. The table that receives changes is `preferences`.

**Comment by herrbischoff** [comment]
Someone already did the work: https://github.com/alexcormier/setwp
