### ISSUE TITLE
Disable bonjour not working

### ISSUE THREAD

**Issue by gfpacheco** [herrbischoff/awesome-osx-command-line#39]
The following command didn't work:

    defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder ProgramArguments -array-add "-NoMulticastAdvertisements"

I'm using El Capitan and the result was this:

    2015-10-23 14:47:16.138 defaults[1547:32276] Could not write domain /System/Library/LaunchDaemons/com.apple.mDNSResponder; exiting

**Comment by herrbischoff** [comment]
Ahh... You need to use sudo of course. ;) I'm going to fix that. Please confirm.

**Comment by gfpacheco** [comment]
I don't think a missing sudo was the problem. I'm getting the exact same result when running the command with sudo:

    sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder ProgramArguments -array-add "-NoMulticastAdvertisements"

Outputs:

    2015-10-24 18:13:51.344 defaults[44088:372595] Could not write domain /System/Library/LaunchDaemons/com.apple.mDNSResponder; exiting

**Comment by herrbischoff** [comment]
Hmm... Maybe try adding `.plist`, like `com.apple.mDNSResponder.plist`. Does that work?

**Comment by gfpacheco** [comment]
Nop, sorry

**Comment by herrbischoff** [comment]
I'm beginning to suspect that this may be due to the new System Integrity Protection feature in El Capitan. If want, you could try rebooting while holding `Cmd-R`, opening the terminal and then enter `csrutil disable`. Restart into your normal system. Then run the Bonjour command again. Does it work now?

To enable SIP again, repeat the above steps but run `csrutil enable`.

**Comment by herrbischoff** [comment]
@gfpacheco: Does my last suggestion work?

**Comment by gfpacheco** [comment]
Sorry, I still didn't have time to try it. I'll try it soon

**Comment by herrbischoff** [comment]
No news is good news. Closing.

**Comment by wallter** [comment]
Adding the **`.plist`** fixed the error on my machine:

`$ sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist ProgramArguments -array-add "-NoMulticastAdvertisements"`

_There were two files in the directory: `com.apple.mDNSResponder.plist` and       `com.apple.mDNSResponderHelper.plist` _

OS X El Capitan Version 10.11.2 (15C50)
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by ryanshuck** [comment]
Walter - did you do anything else? I can't replicate the fix that you did, even with SIP turned off.

**Comment by ryanshuck** [comment]
After a little more work, I found a repeatable process.

In recovery, run 
csrutil disable && reboot
Once back in OS X, log in as an admin user and run 
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
sudo defaults write /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist ProgramArguments -array-add "-NoMulticastAdvertisements"
sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
Reboot and go back into recovery and run
csrutil enable && reboot

That worked for me.

**Comment by mindfulmonk** [comment]
@herrbischoff please re-open, adding .plist didn't work for me either. @ryanshuck solutions works though

**Comment by wKovacs64** [comment]
Temporarily disabling SIP worked for me. As a side note, the plist file was XML beforehand. It is now an "Apple binary property list". Seems fine, though.

**Comment by GitTheHellOutaHere** [comment]
Didn't work for me.

I just went through the entire disable SIP>reboot>run commands>re-enable SIP process.
mDNSResponder is still active and using RAM.

OS X 10.11.6

**Comment by herrbischoff** [comment]
You do realize that mDNSResponder absolutely needs to run because it's the local macOS DNS client, do you? Right, didn't think so.

This command turns off picking up multicast advertisements (Zeroconf/Bonjour/Avahi). The fact that mDNSResponder still runs only indicates that you have been unsuccessful in mangling your system beyond usability but have otherwise probably achieved what you were looking for.

You should really know about what exactly these things do **before** you disable SIP and/or run system level commands you find on the internet.

**Comment by GitTheHellOutaHere** [comment]
Thanks for the reply - it's always nice to wake up to a snarky retort.
Thankfully my system hasn't been "mangled" so that I may respond.

BTW, you might investigate your Dictionary app sometime, because you used "mangled" incorrectly.

> severely mutilate, disfigure, or damage by cutting, tearing, or crushing.

I _thought_ mDNSResponder was necessary, but then while trying prevent more processes from calling home I ran across some pages discussing it and Bonjour and ways to disable it. Nowhere did they mention that mDNSResponder is essential and that entering the commands only disables the discovery ability, not actually mDNSResponder itself. Nor did they describe a method of testing to see if discovery was in fact disabled or not after entering the commands.

I'm not sure the steps are necessary anyway since checking the box to **Disable all incoming connections** in the firewall pane also blocks Bonjour.

> The firewall will block all sharing services, such as file sharing, screen sharing, Messages, Bonjour, and iTunes music sharing.

I hope your day gets better for you. Keep workin' on it...good luck.

**Comment by stefansundin** [comment]
Apparently this is possible without disabling SIP:
```
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true
```

See https://derflounder.wordpress.com/2016/08/22/disabling-bonjour-advertisement-on-os-x-el-capitan-and-later/
