### ISSUE TITLE
Question: What about command line Apps?

### ISSUE THREAD

**Issue by mischah** [herrbischoff/awesome-osx-command-line#81]
Hi, this is really an awesome list :ok_hand: 

I wonder if command line apps would have there place in this list.
It seems that it mainly lists bash commands. Am I right?

Otherwise I would like to add my [iTunes CLI](https://github.com/mischah/itunes-remote) :octocat: 

But there are way more awesome CLI Apps not just for OS X.
Therefore I guess I have to create an »awesome-cli-apps« list :relaxed: 
There is enough material in different categories.

Michael

**Comment by ursooperduper** [comment]
I'd be very psyched about a CLI app list! :+1:

**Comment by herrbischoff** [comment]
Hi there! Thanks for the kind words. I feel that an OS X command line list is not quite the right place for additions like yours. That being said, I have come across a lot of questions and material that could benefit from a nicely curated list. Therefore, @mischah, I hope you excuse my enthusiasm in setting up such a list myself: https://github.com/herrbischoff/awesome-command-line-apps

It's very, very basic right now, but I will keep adding interesting material to it.

Please feel free to add to your hearts' content. And since @mischah is the originator of that idea (or at least the spark that finally lit the fuse), I'll gladly add you as a collaborator with full push privileges if you're interested.

**Comment by mischah** [comment]
Uhm … You ripped my idea without checking my Github repos to check if I already set up this list :open_mouth: 

Here is my list: https://github.com/mischah/awesome-cli-apps

>  Therefore, @mischah, I hope you excuse my enthusiasm in setting up such a list myself: https://github.com/herrbischoff/awesome-command-line-apps

Sorry, that’s feels kinda lame to me. :unamused:

Now we have two lists with the same purpose in the making. Which doesn’t make sense.

**Comment by mischah** [comment]
Update: I’ll delete my list because I finally found [Awesome CLI](https://github.com/aharris88/awesome-cli).

**Comment by herrbischoff** [comment]
Well, what can I say...

**Comment by mischah** [comment]
No Problem man. I just was pissed for a minute or two.

**Comment by herrbischoff** [comment]
@mischah: You're still very welcome to contribute. The existing lists appear very fragmented, partial and sometimes even confusing to me. For me it's not about the GitHub "stars" or the recognition — whatever that means — because that's fleeting and unsubstantial. I just want to build a list that I wish I came about when I was searching. So, how about building that together?

**Comment by mischah** [comment]
> The existing lists appear very fragmented, partial and sometimes even confusing to me.

You’re right. But the guy maintaining »Awesome CLI« knows about the problems and is asking for help.

→ https://github.com/aharris88/awesome-cli/issues/14

> So, how about building that together?

Or we both could contribute to the existing one and help @aharris88 to make a proper awesome list out of his awesome list.

**Comment by aharris88** [comment]
That would be great! And actually, yesterday I was actually thinking renaming it from `awesome-cli` to `awesome-cli-apps`.

**Comment by herrbischoff** [comment]
@aharris88: Renaming it and strengthening its focus would surely go a long way.

**Comment by mischah** [comment]
@aharris88 Count me in. Let’s continue over there.

**Comment by aharris88** [comment]
@mischah  Sounds good. Thanks.
